# Site
repository: TonysHub/TonysHub.github.io 
favicon: images/favicon.ico

version: 2

# Personal info
name: 이동수
title: 데이터를 활용하는 백엔드 엔지니어
email: leegreen123@naver.com
website: https://velog.io/@tonys_hub

# Social links
# twitter_username: sproogen
github_username: TonysHub
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: the_second_loft
linkedin_username: tonyleedongsoo
# pinterest_username:
youtube_username: channel/UCvL8YftvoKcb_XPUHBCh8hw

# About Section
# about_title: About Me
about_profile_image: images/profile2.png
about_content: |
  안녕하세요, 토론토에서 날아온 Django & Python / AWS & Docker 기반의 백엔드 개발자입니다. :rocket: <br>
  캐나다에서는 학업을 병행하며 방학마다 인턴 기회를 찾아다녔습니다. <br>
  **누적 투자액 3조원**의 벤쳐 캐피탈, **일 주문 2만건** 이상의 식료품 서비스 앱 회사에서 총 16개월 데이터 사이언티스트 인턴으로 근무하며
  Ad-tech 사업에 관한 이해도를 높이며, 고객 코호트 분석과 Amplitude 데이터 스키마 구축을 했습니다. <br>
  기존 경력을 활용하여, REST API와 인프라를 구성할 때도 데이터 활용 가능성을 고려하며, 데이터 보안을 우선 시 하는 개발자입니다. <br> 
  업무 / 프로젝트 활용 기술:
  <mark>Django</mark>, 
  <mark>AWS</mark>,
  <mark>Docker</mark>,
  <mark>Postgres</mark>,
  <mark>Airflow</mark>. <br>
  
  학교 졸업 후 한국으로 돌아와 특전사로 18개월 군 복무(2021.06 ~ 2022.12)를 마치고, 현재 프로그래머스 데이터 엔지니어링 데브코스 수강(2023.05~2023.09)과 개인 프로젝트를 병행하고 있습니다. <br>
  데브코스에는 팀장 역할을 맡으며, 다른 팀원들이 교육을 잘 따라올 수 있도록 리드하고 있습니다.

content:
 

  - title: 프로젝트
    layout: list
    content:
      - layout: left
        border: weak
        title: Collaberr
        sub_title: Django 백엔드 개발자 
        dates: 2023.06 ~ 현재
        additional_links:
          - title: Collaberr-backend
            icon: fab fa-github
            url: https://github.com/TonysHub/collaberr-backend
        quote: >
          해외 마케팅 팀을 채용/운영 할 여력이 없는 중소기업에게 해외 마케팅을 PaaS 형태로 제공 <br>

        description: |
          * Django를 활용한 **REST API**와 데이터 스키마 구축, 서버 배포 담당
          * Docker를 사용한 획일화된 테스팅 환경 설정과 GitHub Action을 통해 [DockerHub](https://hub.docker.com/repositories/tonylee9692)와 연동 CI 구축
          * Django-split-settings를 적용하여, **개발 및 배포 환경 분리**
          * **유저 데이터 보안**을 최우선으로 생각하여, 민감 정보는 모두 server-side에서 Http Only Cookie로 처리 (JWT, CSRF, Youtube API Token 등)
          * AWS의 Least Privilege를 모티브로 API request에서 최대한 제한적인 권한 설정
          * 테스팅용 컨테이너에 Postgres & Pgadmin을 연결하여 개발 최적화
          * 현재 개발 진행중, <mark>프로젝트 리드</mark>

      - layout: left
        border: weak
        title: 영화 트렌드 대시보드 
        subtitle: 팀장, 배포 및 인프라 설계
        dates: 2023.05.29 - 2023.06.02 (5일)
        additional_links:
          - title: 영화 트렌드 대시보드
            icon: fab fa-github
            url: https://github.com/data-dev-course/project2-team2
        quote: >
          영화 진흥위원회 Open API를 활용하여 데이터 분석 대시보드를 만드는 데브코스 프로젝트 <br>
        description: |
          * [AWS 인프라를 개인적으로 공부](https://velog.io/@tonys_hub?tag=Knowledge)하여, 현업에서 쓰이는 구조와 동일한 [인프라](https://user-images.githubusercontent.com/43350428/242866357-a54e009f-0ec3-4b9d-8311-f5f19a28e08c.png) 구성 
          * **Bastion Host를 사용**함으로써 Private subnet의 접근을 제한하며, NAT Gateway를 통해 API 호출 후 Gateway Endpoint로 S3 버킷에 적재
          * 같은 Region 안에 있는 버킷임으로 Gateway Endpoint로 비용 최소화
          * S3의 **Object-based Storage** 특성을 활용하여, 매일 추출한 데이터를 Over-ride 하는 방식 적용
          * Amazon SageMaker를 이용하여, 당일 영화 매출 예측 후 predicted_sales 컬럼에 저장
          * S3에 당일 데이터가 저장되면, EventBridge를 이용하여, Redshift에 ETL 진행
          * 프로젝트 진행 도중 Redshift Serverless의 비용이 많이 나오는 것을 인지하여, **Amazon ElastiCache Redis 적용**
          * Superset을 EC2 프리티어 인스턴스에 띄운 후, 대시보드 제작
          * 프로젝트 팀장으로써, 각 조원의 성향과 역량을 고려하여 트렐로 티켓 배정
          * <mark>인프라 총괄</mark>
          
      - layout: left
        border: weak
        title: Subway Infographics
        sub_title: 팀장, Django 백엔드
        link: https://github.com/TonysHub/subway
        dates: 2023.05.01 - 2023.05.05 (5일)
        additional_links: 
          - title: Subway Infographics
            icon: fab fa-github
            url: https://github.com/TonysHub/subway
        description: |
          * 

      - layout: left
        border: weak
        title: Lumos Lux
        sub_title: 데이터 분석 및 검증
        dates: 2020.08 - 2021.06
        description: |
          * 불면증 개선을 위한 스마트 Light-Therapy Glasses
          * 시장 데이터 분석, 고객 만족도 검증, Mechanical Design 담당
          * 높은 고객 만족도와 불면증치료 업계의 집중을 받으며, [Stanford University Dr.Jamie Zeitzer](https://profiles.stanford.edu/jamie-zeitzer) 교수님과 광학 연구 협업
          * [ANSYS Design Analytics Award, 1등](https://uwaterloo.ca/engineering-ideas-clinic/design-analysis-competition)
          * [SFF 온타리오주 Engineering Competition 혁신 디자인, 2등](https://www.instagram.com/p/CKrCyEUJ4pP/) (매년 링크 초기화로, 인스타그램만 남아있음)
          * [Baylis Medical Capstone Design 수상](https://www.eng.uwaterloo.ca/2021-capstone-design/mechanical/participants-2/)
          * 광선요법 치료 특허 출원, Google Patents [CA3081398A1](https://patents.google.com/patent/CA3081398A1/en?oq=CA3081398A1) (성명 오타)
          
  - title: 역량 # title for the section
    layout: list
    content:
      - layout: left
        border: weak
        title: collaberr
        link: https://github.com/tonyshub/collaberr-backend
        additional_links:
          - title: collaberr-backend
            icon: fab fa-github
            url: https://github.com/tonyshub/collaberr-backend
        quote: >
          해외 마케팅 팀을 채용/운영 할 여력이 없는 중소기업에게 해외 마케팅을 PaaS 형태로 제공
        description: |
          * Django를 활용한 REST API와 데이터 스키마 구축, 서버 배포 담당
          * 스코프가 큰 프로젝트인 만큼 번아웃을 방지하며, 2023년 말까지 AWS 서버에 배포 예정
          * 도커를 사용한 획일화된 테스팅 환경 설정
          
      - layout: top-middle
        title: itsgoingto.be
        link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          itsgoingto.be is a simple voting site where a user can ask a question or topic top put to a vote. This question
          can then be shared with their friends/colleagues to vote on things like 'Where should we go for lunch?'.
        description: |
          The API for this site has been build using <mark>Node.js</mark> while the front end is a <mark>React</mark>/<mark>Redux</mark> app.
          I have used <mark>Docker</mark> to set up a development environment and <mark>Heroku</mark> to deploy and host the site. I have
          a suite of unit and API tests for the backend and unit tests for the front end.

          I have been using this project as a way to increase many of my skills and also learn new things, most recently sockets and Node.JS. I have particually
          enjoyed managing my own project and designing my own architecture and implementing this to a high standard.

          Feel free to check out the whole project on GitHub to get a feel for how I work [here](https://github.com/sproogen/itsgoingto.be).

  - title: Education
    layout: list
    content:
      - title: University of Waterloo
        sub_title: 기계공학과, 우등학사 (B.A.Sc, Honors)
        caption: 2015.06 - 2021.06
        description: |
          * President's 입학 장학금 수료
          * 졸업작품 각종 대회 수상

  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
      mountain biking, road cycling, kitesuring and horse riding as well as trying to make time for things like
      rock climbing and playing some rugby. I currently have 2 horses and find this is a great way to get out of the house
      and taking my mind of things while learing to showjump.

      I'm interested in photography and videography as I like to be creative, this is mainly through sport but
      I enjoy landscape and abstract photography too. I like to showcase my work on instagram if
      you would like to take a look - [jameswgrant](https://www.instagram.com/jameswgrant/).

      Finally during the rest of my free time you will either find me working on my bikes, rock climbing at one of
      Bristol's indoor climbing centres or down 'The Rec' supporting Bath Rugby.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed

gems: ["jemoji"]
